/**
 * @file markdown.js
 * Renders structured log analysis results into AI-optimized Markdown
 * identical to log_compressor.py output structure.
 */

import { SEVERITY_LEVELS, SEVERITY_ICONS } from './constants.js';

function plural(n, word) {
  return `${n} ${word}${n !== 1 ? 's' : ''}`;
}

/**
 * Renders Markdown report matching log_compressor.py.
 * 
 * @param {string} filename 
 * @param {object} session 
 * @param {Array<{ time: string, sceneName: string }>} sceneEvents 
 * @param {object} groups 
 * @param {Array<{ time: string, severity: string, label: string, clean: string }>} timeline 
 * @param {number} [maxGroup=5] 
 * @returns {string}
 */
export function renderMarkdown(filename, session, sceneEvents, groups, timeline, maxGroup = 5) {
  const lines = [];
  const W = (line) => lines.push(line);

  W(`# Unity Log Analysis — \`${filename}\``);
  W('');
  W('<!-- Generated by Unity Log Analyzer — optimized for AI context -->');
  W('');

  // ── Session overview ──
  W('## Session Overview');
  W('');
  W('| | |');
  W('|---|---|');
  W(`| **Time range** | \`${session.start}\` → \`${session.end}\` |`);
  W(`| **Total lines** | ${Number(session.total_lines).toLocaleString('en-US')} |`);
  W(`| **Scenes loaded** | ${session.scenes} |`);
  W(`| 🔴 Exceptions | ${session.exceptions} |`);
  W(`| 🟠 Errors | ${session.errors} |`);
  W(`| 🟡 Warnings | ${session.warnings} |`);
  W(`| ⚪ Log events | ${session.logs} |`);
  W('');

  // ── Scenes ──
  if (sceneEvents && sceneEvents.length > 0) {
    W('## Scene Timeline');
    W('');
    for (const ev of sceneEvents) {
      W(`- \`${ev.time}\` → **${ev.sceneName}**`);
    }
    W('');
  }

  // ── Critical events (grouped) ──
  W('## Critical Events (Grouped)');
  W('');
  W('> Each group shows: total occurrences, representative context, and first/last timestamp.');
  W('');

  const groupEntries = Object.entries(groups || {});
  groupEntries.sort((a, b) => {
    const sevWeightA = SEVERITY_LEVELS[a[1].severity] || 0;
    const sevWeightB = SEVERITY_LEVELS[b[1].severity] || 0;
    if (sevWeightB !== sevWeightA) {
      return sevWeightB - sevWeightA;
    }
    return (b[1].occurrences?.length || 0) - (a[1].occurrences?.length || 0);
  });

  for (const [cat, info] of groupEntries) {
    const sev = info.severity;
    const label = info.label;
    const occ = info.occurrences || [];
    const icon = SEVERITY_ICONS[sev] || '⚪';
    const count = occ.length;

    const timesWithData = occ.filter((o) => o.time);
    const firstTs = timesWithData.length > 0 ? timesWithData[0].time : 'N/A';
    const lastTs = timesWithData.length > 0 ? timesWithData[timesWithData.length - 1].time : 'N/A';
    const timeRange = firstTs === lastTs ? `\`${firstTs}\`` : `\`${firstTs}\` → \`${lastTs}\``;

    W(`### ${icon} ${label} — ${plural(count, 'occurrence')}`);
    W('');
    W(`**Category:** \`${cat}\` | **Severity:** \`${sev}\` | **When:** ${timeRange}`);
    W('');

    let shown = 0;
    for (const o of occ) {
      if (!o.time) {
        continue; // deduplicated, no context stored
      }
      if (shown >= maxGroup) {
        W(`_...and ${count - shown} more occurrences (omitted for brevity)_`);
        break;
      }
      if (o.context && o.context.length > 0) {
        W(`**Context before** (\`${o.time}\`):`);
        W('```');
        for (const c of o.context) {
          W(c);
        }
        W('```');
      } else {
        W(`- \`${o.time}\` _(no distinct context lines)_`);
      }
      shown++;
    }

    if (shown === 0) {
      W(`_All ${count} occurrences were rapid repeats within the deduplication window._`);
    }

    W('');
  }

  // ── Timeline ──
  W('## Event Timeline');
  W('');
  W('_One entry per scene load + first occurrence of each error type per minute._');
  W('');

  for (const item of timeline || []) {
    const icon = SEVERITY_ICONS[item.severity] || '⚪';
    W(`- \`${item.time}\` ${icon} **${item.label}** — ${item.clean}`);
  }

  W('');

  // ── Prompt suggestion ──
  W('---');
  W('');
  W('## Suggested Prompt');
  W('');
  W('> Copy everything above this section and prepend the following:');
  W('');
  W('```');
  W('The following is a compressed Unity runtime log from a game session.');
  W('Repeated events are grouped. Context lines show what happened just before each error.');
  W('');
  W('Please:');
  W('1. Identify the most likely root causes for the critical errors.');
  W('2. Note any error cascades (one error triggering others).');
  W('3. Suggest specific fixes, referencing the context lines where relevant.');
  W('4. Flag any patterns that suggest systemic issues (not one-off bugs).');
  W('```');
  W('');

  return lines.join('\n');
}
